apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/lichen782/ttc-connectors-ranking:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/lichen782/ttc-connectors-ranking:{{.DIGEST_HEX}}"
    local: {}
  deploy:
    helm:
      releases:
      - name: ttc-connectors-ranking
        chartPath: charts/ttc-connectors-ranking
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/lichen782/ttc-connectors-ranking"
          image.tag: "{{.TAG}}"
